language: node_js
dist: trusty
sudo: required
node_js: 10
install:
  - npm install -g yarn
  - yarn global add purescript@^0.12 pulp bower purescript-psa
  - export PATH="$PATH:`yarn global bin`"
  - bower install
  - yarn install
script:
  - pulp test
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
